import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-6 py-2 bg-gray-700 flex justify-center gap-x-14 text-white font-bold text-xl">
          <a className="rounded-full bg-yellow-500/50 px-6 py-2" href="/">Home</a>
          <a className="rounded-full bg-yellow-500/50 px-6 py-2"  href="/counter">Counter</a>
          <a className="rounded-full bg-yellow-500/50 px-6 py-2"  href="/effect">Effect</a>
          <a className="rounded-full bg-yellow-500/50 px-6 py-2"  href="/fruits">Fruits</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
