import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartContextProvider } from "@/context/CartContext";
import Cart from "@/components/Cart";
import ToastProvider from "@/components/Toast/ToastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider>
          <ToastProvider/>
          <div className="flex flex-row justify-between m-auto w-[70%]">
            <Cart/>
          </div>
          {children}
        </CartContextProvider>
      </body>
    </html>
  );
}
