import type { Metadata } from "next";
//import localFont from "next/font/local";
//import "./globals.css";

import Header from "../components/header"
import Footer from "../components/footer"
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor:"#e7d8c9", color:"#0f4c5c", fontFamily:"verdana", fontSize:"18px"}}>  
        <Header/>
        <div style={{ height:"100px", marginTop:"50px"}}>
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
